[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
TALOSCONFIG = "{{config_root}}/bootstrap/talos/clusterconfig/talosconfig"
SOPS_AGE_KEY_FILE = "/home/rize/.ssh/key.txt"

[tools]
helmfile = "1.2.2"
sops = "3.10.2"
talhelper = "3.0.36"
