[env]
KUBECONFIG = "{{config_root}}/infrastructure/oracle/terraform/kubeconfig"
TALOSCONFIG = "{{config_root}}/infrastructure/oracle/terraform/talosconfig"
SOPS_AGE_KEY_FILE = "/home/rize/.ssh/key.txt"

[tools]
helmfile = "1.1.4"
sops = "3.10.2"
talhelper = "3.0.36"
