apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: homelab
spec:
  resources:
    requests:
      storage: 200Gi
#  storageClassName: piraeus-replicated
  accessModes:
    - ReadWriteMany
