apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - variables.yaml
  - rook-ceph.yaml
  - homelab.yaml
  - cert-manager.yaml
  - envoy-gateway-system.yaml
  - homepage.yaml
  - observability.yaml
  - snapshot-controller.yaml
