apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - victoria-metrics
  - bjw-s-helmrepository.yaml
  - intel-device-plugins-for-kubernetes
  - cert-manager
  - fluent-bit
